### ISSUE TITLE
Pigeon ribbon connector is 180' from correct position

### ISSUE THREAD

**Issue by ozrien** [CrossTheRoadElec/Device-CADs#2]
CAD for Pigeon has the ribbon cable connector placed such that the keyed side is on the outside, instead of  on the inside.

**Comment by JCaporuscio** [comment]
MacFarlane fixed it this morning and is sending me a new file to update on the website.

I'll make sure it gets up here at the same time.

**Comment by macfarmi** [comment]
fixed
